server:
  port: 8001
  servlet:
    context-path: /dept

spring:
  application:
    name: microservicecloud-dept
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 1
      #logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    width: 150
    height: 150
  tracker-list: 182.254.171.122:22122
  excelTemplate:
    employeeInfo: group1/M00/00/00/tv6remA8XbqAO5MBAABKAAyXSP0630.xls
#    residentInfo: group1/M00/00/18/Cs6OzV5RCb-AI1voAAAzDcl-gwY31.xlsx
#    buildingInfo: group1/M00/00/27/Cs6OzV5YmiyAdxOxAAAjEpzOseE25.xlsx
#    houseInfo: group1/M00/00/27/Cs6OzV5YmjiAfoZCAAAkoM7e6mY10.xlsx
#    parkingInfo: group1/M00/00/27/Cs6OzV5YmkWAJw_oAAAj0NWn5SU98.xlsx
#    communityInfo: group1/M00/00/27/Cs6OzV5YmhSAHfirAAAm5tzcL9A26.xlsx
#    unpaybill: group1/M00/00/22/Cs6OzV5XX-OAcamZAAAqs0yXT5c67.xlsx
#    payedbill: group1/M00/00/22/Cs6OzV5XX8mANmJmAAAr5Y7_Pik06.xlsx
